apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluxora.fullname" . }}-frontend
  labels:
    app: fluxora-frontend
spec:
  type: {{ .Values.service.frontendType }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: fluxora-frontend
