apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluxora.fullname" . }}-backend
  labels:
    app: fluxora-backend
spec:
  type: {{ .Values.service.backendType }}
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: fluxora-backend
